spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///home/pantoja/dev/workspace/microservices-lab/spring-microservices/git-localconfig-repo
server:
  port: 8888

