spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
#      http://localhost:8001/h2-console / jdbc:h2:mem:testdb
server:
  port: 8000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
